Repository sena-proyectos/Siscomite, pull requests merged in 2023-08, with the labels that each got.

#4 Updated About - readme
  README.md
Labels: documentation

#5 Update Database
  server/src/db/DB.sql
Labels: enhancement

#7 token endpoint running, update, create, get
  server/src/controller/fichas.controller.js
  server/src/middlewares/fichas.middleware.js
  server/src/routes/fichas.routes.js
  server/src/schemas/fichas.schemas.js
Labels: enhancement

#13 Endpoint and bug
  .vscode/settings.json
  server/src/config.js
  server/src/controller/apprentices.controller.js
  server/src/controller/article.controller.js
  server/src/controller/cause.controller.js
  server/src/controller/documents.controller.js
  server/src/controller/fichas.controller.js
  server/src/controller/modalities.controller.js
  server/src/controller/request.controller.js
  server/src/controller/user.controller.js
  server/src/index.js
  server/src/middlewares/apprentices.middlewares.js
  server/src/middlewares/article.middlewares.js
  server/src/middlewares/cause.middlewares.js
  server/src/middlewares/documents.middlewares.js
  server/src/middlewares/modalities.middlewares.js
  server/src/middlewares/request.middlewares.js
  server/src/middlewares/user.middleware.js
  server/src/routes/apprentices.routes.js
  server/src/routes/article.routes.js
  server/src/routes/cause.routes.js
  server/src/routes/documents.routes.js
  server/src/routes/fichas.routes.js
  server/src/routes/modalities.routes.js
  server/src/routes/request.routes.js
  server/src/schemas/apprentices.schema.js
  server/src/schemas/article.schema.js
  server/src/schemas/cause.schemas.js
  server/src/schemas/documents.schemas.js
  server/src/schemas/fichas.schemas.js
  server/src/schemas/modalities.schema.js
  server/src/schemas/request.schemas.js
  server/src/schemas/solicited.schemas.js
  server/src/schemas/user.schemas.js
Labels: bug
